name: CI

# Triggers: run on pushes and pull requests to any branch
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      # optional: upload test logs as artifact (uncomment if you want)
      - name: Upload test logs
        uses: actions/upload-artifact@v4
         with:
           name: pytest-report
           path: pytest-report.log
